preserve_directory_names: true
nav:
  - Home:
    - index.md
    - AirFryer.md
    - Contacts.md
    - Calendar.md
    - Breakfast.md
    - Hospitals.md
    - Meal.md
    - Clothing Sizes.md
  - Snacks: Snacks
  - Food: Food
  - Beverages: Beverages
  - How To: HowTo
